<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="user.aspx.cs" Inherits="UNEOPACS2.admin.user" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>จัดการผู้ใช้งาน</title>
        <link href="../Scripts/MDB-Free_4.8.10/css/bootstrap.css" rel="stylesheet" />
    <link href="../Scripts/MDB-Free_4.8.10/css/mdb.css" rel="stylesheet" />

    <script src="../Scripts/jquery-3.4.1.min.js"></script>
    <script src="../Scripts/MDB-Free_4.8.10/js/bootstrap.js"></script>
    <script src="../Scripts/MDB-Free_4.8.10/js/mdb.js"></script>
    <script src="../Scripts/MDB-Free_4.8.10/js/popper.min.js"></script>

    <style>
        body{
background-image: linear-gradient(to right bottom, #fcfcfc, #f4f3f4, #ecebeb, #e4e2e3, #dcdada);
        }
    </style>
</head>
<body>


    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CssClass="table table-hover mb-0" DataKeyNames="user_id" DataSourceID="sqlUser" ShowHeaderWhenEmpty="True" CellPadding="4" ForeColor="#333333" GridLines="None">
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                <Columns>
                    <asp:BoundField DataField="user_id" HeaderText="user_id" SortExpression="user_id" />
                    <asp:BoundField DataField="user_pass" HeaderText="user_pass" SortExpression="user_pass" Visible="False" />
                    <asp:BoundField DataField="fullname" HeaderText="fullname" SortExpression="fullname" />
                    <asp:CheckBoxField DataField="report" HeaderText="report" SortExpression="report" />
                    <asp:BoundField DataField="ondate" HeaderText="ondate" SortExpression="ondate" />
                    <asp:BoundField DataField="ipaddress" HeaderText="ipaddress" SortExpression="ipaddress" />
                    <asp:BoundField DataField="timeout" HeaderText="timeout" SortExpression="timeout" />
                    <asp:BoundField DataField="access" HeaderText="access" SortExpression="access" />
                    <asp:CheckBoxField DataField="logedin" HeaderText="logedin" SortExpression="logedin" Visible="False" />
                </Columns>
                <EditRowStyle BackColor="#999999" />
                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
            </asp:GridView>
            <asp:SqlDataSource ID="sqlUser" runat="server" ConnectionString="<%$ ConnectionStrings:PACS %>" DeleteCommand="DELETE FROM [Userlogin] WHERE [user_id] = @user_id" SelectCommand="SELECT * FROM [Userlogin]" UpdateCommand="UPDATE Userlogin SET fullname =@fullname, report =@report, ondate =@ondate, ipaddress =@ipaddress, timeout =@timeout, access =@access WHERE [user_id] = @user_id">
                <DeleteParameters>
                    <asp:Parameter Name="user_id" />
                </DeleteParameters>
                <UpdateParameters>
                    <asp:Parameter Name="fullname" />
                    <asp:Parameter Name="report" />
                    <asp:Parameter Name="ondate" />
                    <asp:Parameter Name="ipaddress" />
                    <asp:Parameter Name="timeout" />
                    <asp:Parameter Name="access" />
                    <asp:Parameter Name="user_id" />
                </UpdateParameters>
            </asp:SqlDataSource>
        </div>
    </form>
</body>
</html>
